# Generated by Django 3.1.2 on 2020-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201014_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_stock',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
