# Generated by Django 3.1.2 on 2020-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='', upload_to='user_image/'),
        ),
    ]
