# Generated by Django 3.1.2 on 2020-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='total_qty',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
